### ISSUE TITLE
Two crashes in the same location.

### ISSUE THREAD

**Issue by K0-RR** [TeamMidnightDust/ThisRocks#7]
I got a crash in nether, restarted the game, went to the nether again and after few seconds I got another crash in the same location. I don't have latest.log.

```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2020-12-12 23:38:33 CET
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property class_2754{name=variation, clazz=class eu.midnightdust.motschen.rocks.blockstates.StarfishVariation, values=[red, pink, orange]} as it does not exist in Block{minecraft:air}
    at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.1)
    at net.minecraft.state.State.get(State:95)
    at eu.midnightdust.motschen.rocks.block.blockentity.StarfishBlockEntity.getVariation(StarfishBlockEntity.java:14)
    at eu.midnightdust.motschen.rocks.block.render.StarfishBlockEntityRenderer.render(StarfishBlockEntityRenderer.java:78)
    at eu.midnightdust.motschen.rocks.block.render.StarfishBlockEntityRenderer.render(StarfishBlockEntityRenderer.java:17)
    at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.render(BlockEntityRenderDispatcher:107)
    at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.method_23081(BlockEntityRenderDispatcher:96)
    at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.runReported(BlockEntityRenderDispatcher:128)
    at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.render(BlockEntityRenderDispatcher:96)
    at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:302)
    at net.minecraft.client.render.WorldRenderer.handler$cfi000$onRenderTileEntities(WorldRenderer:9216)
    at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1265)
    at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:727)
    at net.minecraft.client.render.GameRenderer.render(GameRenderer:546)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:1048)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
    at net.minecraft.client.main.Main.main(Main:215)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Block Entity Details --
  Name: rocks:starfish_blockentity // eu.midnightdust.motschen.rocks.block.blockentity.StarfishBlockEntity
  Block: Block{rocks:starfish}[variation=pink,waterlogged=true]
  Block location: World: (-33,67,60), Chunk: (at 15,4,12 in -3,3; contains blocks -48,0,48 to -33,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Block: Block{minecraft:air}
  Block location: World: (-33,67,60), Chunk: (at 15,4,12 in -3,3; contains blocks -48,0,48 to -33,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Block Entity NBT: {x:-33,y:67,z:60,id:"rocks:starfish_blockentity"}

-- Affected level --
  All players: 1 total; [class_746['_K0RR_'/246, l='ClientLevel', x=-10.51, y=81.00, z=54.87]]
  Chunk stats: SodiumChunkCache: 403
  Level dimension: minecraft:the_nether
  Level spawn location: World: (-176,78,240), Chunk: (at 0,4,0 in -11,15; contains blocks -176,0,240 to -161,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Level time: 49116 game time, 622152 day time
  Server brand: fabric
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.16.4
  Minecraft Version ID: 1.16.4
  Operating System: Linux (amd64) version 5.4.70-amd64-desktop
  Java Version: 1.8.0_275, BellSoft
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), BellSoft
  Memory: 3415912416 bytes (3257 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
  CPUs: 8
  JVM Flags: 8 total; -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=51 -XX:G1HeapRegionSize=32M -Xms8192m -Xmx8192m
  Suspected Mods: Sodium (sodium), This Rocks! (rocks), Fabric Loader (fabricloader)
```

```
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 2020-12-12 23:42:02 CET
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property class_2754{name=variation, clazz=class eu.midnightdust.motschen.rocks.blockstates.StarfishVariation, values=[red, pink, orange]} as it does not exist in Block{minecraft:soul_soil}
    at Not Enough Crashes deobfuscated stack trace.(1.16.4+build.1)
    at net.minecraft.state.State.get(State:95)
    at eu.midnightdust.motschen.rocks.block.blockentity.StarfishBlockEntity.getVariation(StarfishBlockEntity.java:14)
    at eu.midnightdust.motschen.rocks.block.render.StarfishBlockEntityRenderer.render(StarfishBlockEntityRenderer.java:78)
    at eu.midnightdust.motschen.rocks.block.render.StarfishBlockEntityRenderer.render(StarfishBlockEntityRenderer.java:17)
    at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.render(BlockEntityRenderDispatcher:107)
    at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.method_23081(BlockEntityRenderDispatcher:96)
    at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.runReported(BlockEntityRenderDispatcher:128)
    at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.render(BlockEntityRenderDispatcher:96)
    at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:302)
    at net.minecraft.client.render.WorldRenderer.handler$cfi000$onRenderTileEntities(WorldRenderer:9216)
    at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1265)
    at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:727)
    at net.minecraft.client.render.GameRenderer.render(GameRenderer:546)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:1048)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
    at net.minecraft.client.MinecraftClient.handler$bbk000$afterCrashHandled(MinecraftClient:10904)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:699)
    at net.minecraft.client.main.Main.main(Main:215)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Block Entity Details --
  Name: rocks:starfish_blockentity // eu.midnightdust.motschen.rocks.block.blockentity.StarfishBlockEntity
  Block: Block{rocks:starfish}[variation=orange,waterlogged=false]
  Block location: World: (-18,78,62), Chunk: (at 14,4,14 in -2,3; contains blocks -32,0,48 to -17,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Block: Block{minecraft:soul_soil}
  Block location: World: (-18,78,62), Chunk: (at 14,4,14 in -2,3; contains blocks -32,0,48 to -17,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Block Entity NBT: {x:-18,y:78,z:62,id:"rocks:starfish_blockentity"}

-- Affected level --
  All players: 1 total; [class_746['_K0RR_'/3798, l='ClientLevel', x=-8.85, y=88.53, z=43.90]]
  Chunk stats: SodiumChunkCache: 1249
  Level dimension: minecraft:the_nether
  Level spawn location: World: (-176,78,240), Chunk: (at 0,4,0 in -11,15; contains blocks -176,0,240 to -161,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Level time: 50050 game time, 623086 day time
  Server brand: fabric
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.16.4
  Minecraft Version ID: 1.16.4
  Operating System: Linux (amd64) version 5.4.70-amd64-desktop
  Java Version: 1.8.0_275, BellSoft
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), BellSoft
  Memory: 3142248416 bytes (2996 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
  CPUs: 8
  JVM Flags: 8 total; -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=51 -XX:G1HeapRegionSize=32M -Xms8192m -Xmx8192m
  Suspected Mods: Sodium (sodium), This Rocks! (rocks), Fabric Loader (fabricloader)
```

**Comment by K0-RR** [comment]
I don't know, is this even worth reporting? Report this to the Sodium team too?

**Comment by Mirsario** [comment]
My friend got the same crash, but we're using OptiFabric + OptiFine, not Sodium, so all 3 may be unrelated?

```[22:04:26] [main/FATAL]: Reported exception thrown!
net.minecraft.class_148: Rendering Block Entity
	at net.minecraft.class_824.method_3554(class_824.java:192) ~[intermediary-fabric-loader-0.10.8-1.16.4.jar:?]
	at net.minecraft.class_824.method_3555(class_824.java:99) ~[intermediary-fabric-loader-0.10.8-1.16.4.jar:?]
	at net.optifine.shaders.ShadersRender.renderShadowMap(ShadersRender.java:446) ~[Optifine-mapped.jar:?]
	at net.optifine.shaders.Shaders.beginRender(Shaders.java:4260) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:949) ~[intermediary-fabric-loader-0.10.8-1.16.4.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:693) ~[intermediary-fabric-loader-0.10.8-1.16.4.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1048) ~[intermediary-fabric-loader-0.10.8-1.16.4.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-fabric-loader-0.10.8-1.16.4.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-fabric-loader-0.10.8-1.16.4.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-loader-0.10.8.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.8.jar:?]
Caused by: java.lang.IllegalArgumentException: Cannot get property class_2754{name=variation, clazz=class eu.midnightdust.motschen.rocks.blockstates.StarfishVariation, values=[red, pink, orange]} as it does not exist in Block{minecraft:void_air}
	at net.minecraft.class_2688.method_11654(class_2688.java:95) ~[intermediary-fabric-loader-0.10.8-1.16.4.jar:?]
	at eu.midnightdust.motschen.rocks.block.blockentity.StarfishBlockEntity.getVariation(StarfishBlockEntity.java:14) ~[rocks-1.2.2.jar:?]
	at eu.midnightdust.motschen.rocks.block.render.StarfishBlockEntityRenderer.render(StarfishBlockEntityRenderer.java:78) ~[rocks-1.2.2.jar:?]
	at eu.midnightdust.motschen.rocks.block.render.StarfishBlockEntityRenderer.method_3569(StarfishBlockEntityRenderer.java:17) ~[rocks-1.2.2.jar:?]
	at net.minecraft.class_824.method_23079(class_824.java:126) ~[intermediary-fabric-loader-0.10.8-1.16.4.jar:?]
	at net.minecraft.class_824.method_23081(class_824.java:101) ~[intermediary-fabric-loader-0.10.8-1.16.4.jar:?]
	at net.minecraft.class_824$$Lambda$5545/1720668011.run(Unknown Source) ~[?:?]
	at net.minecraft.class_824.method_3554(class_824.java:185) ~[intermediary-fabric-loader-0.10.8-1.16.4.jar:?]
	... 15 more```

**Comment by Mirsario** [comment]
After some googling, and running into a similar crash in another mod -- yeah, Sodium & OptiFine are definitely unrelated. Something's just missing BlockState.isAir() checks somewhere, or the block entities don't get removed in time.
